# Generated by Django 4.1.3 on 2022-12-14 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_video_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='link',
            new_name='youtubelink',
        ),
    ]
