# Generated by Django 4.1.3 on 2022-12-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_link_video_youtubelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='youtubelink',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
